- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "Copy TLS files on local filesystem"
      no_log: true
      copy:
        content: "{{ tls_file.content }}"
        dest: "{{ tls_file.dest }}"
        mode: "{{ tls_file.mode }}"
      loop:
        - { content: "{{ (lookup('aws_secret', 'dev/production/tls/certificates') | from_json).get('chain_cert') }}", dest: "/tmp/dev.crt", mode: "0600" }
        - { content: "{{ (lookup('aws_secret', 'dev/production/tls/private_keys') | from_json).get('private_key') }}", dest: "/tmp/dev.key", mode: "0600" }
      loop_control:
        loop_var: tls_file
      # As there is no way to mock 'aws_secret' calls to a real AWS account, we ignore
      # errors as we do not have any AWS credentials in the context of this playbook
      ignore_errors: true